services:
  app:
    command:
      - "python"
      - "app.py"
      - "--port"
      - "8050"
      - "--host"
      - "0.0.0.0"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8050:8050"

